// Generated by CoffeeScript 1.6.2
(function() {
  var App,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = (function() {
    function App() {
      this.onResize = __bind(this.onResize, this);
      this.setupMap = __bind(this.setupMap, this);
      this.render = __bind(this.render, this);
    }

    App.prototype.render = function() {
      try {
        Typekit.load();
      } catch (_error) {}
      document.addEventListener("touchstart", function() {
        return null;
      }, true);
      this.setupMap();
      $(window).on("resize", this.onResize);
      return this.onResize();
    };

    App.prototype.setupMap = function() {
      var map;

      map = L.mapbox.map('map', 'fravic.j11ifpci', {
        attributionControl: false,
        zoomControl: false
      });
      map.dragging.disable();
      map.touchZoom.disable();
      map.doubleClickZoom.disable();
      return map.scrollWheelZoom.disable();
    };

    App.prototype.onResize = function() {};

    App.prototype.isMobile = function() {
      return /Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i.test(navigator.userAgent || navigator.vendor || window.opera);
    };

    return App;

  })();

  window.app = new App();

  $(app.render);

}).call(this);
